source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.1'
gem 'puma', '~> 3.7'
gem 'rack-cors', :require => 'rack/cors'
gem 'devise'
gem 'dotenv-rails'

# database
gem 'sqlite3', group: [:development, :test]
gem 'pg', group: :production
gem 'pg_search'

# serializer
gem 'active_model_serializers', '~> 0.10.6'
gem 'oj'
gem 'oj_mimic_json'

group :development do
  gem 'rubocop', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano', '~> 3.8'
  gem 'capistrano-rvm'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
end

# testing
group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'guard-rspec'
end
